### PR TITLE
build: Add a minimal configure.ac

### PR DESCRIPTION
**Pull request by orbea**
When building with slibtool using the rlibtool symlink the build will fail when it fails to find the generated libtool. This is required so rlibtool can determine if it should build shared or static libraries.

This can be fixed by adding a minimal configure.ac that can generate the required files with autoreconf.

Gentoo Bug: https://bugs.gentoo.org/913482

### CODE REVIEW

**Comment by clason** [comment]
Thank you, but you should propose any such changes to the original maintainer. (Neovim no longer uses this fork.)

**Comment by orbea** [comment]
@clason Mind pointing me in the right direction? I was not sure where else to submit this.

**Comment by orbea** [comment]
The libtermkey site (https://www.leonerd.org.uk/code/libtermkey/) states:

> DEPRECATED
>
> Note: Use of this library for new programs is discouraged. It is being maintained for legacy purposes only. For writing new programs, please use [libtickit](https://www.leonerd.org.uk/code/libtickit/) instead.
>
> All of the code in this library will be migrated into libtickit in due course; currently it is used via an internal dependency.

**Comment by gpanders** [comment]
@orbea Indeed, which is why Neovim has chosen to [vendor libtermkey](https://github.com/neovim/neovim/pull/25870). The author is very reluctant to make a new release. The long term plan is to integrate libtermkey's functionality into libtickit, at which point Neovim _may_ choose to unvendor libtermkey in favor of using libtickit as a dependency.

In any case, as of Neovim 0.10 (the next release) libtermkey should not be seen as a dependency of Neovim by distributors/package maintainers. It is now functionally part of Neovim's own source code.

**Comment by clason** [comment]
Upstream is https://www.leonerd.org.uk/code/libtermkey/

**Comment by orbea** [comment]
That is understandable, thank you for the prompt replies.

**Comment by clason** [comment]
No worries, sorry for getting your hopes up. The intent was never to create a separate maintained fork for other downstream users. It's probably best to archive this repo sooner rather than later in order to prevent further misunderstandings.

**Pull request closed without merging**
